---
#项目名称
name: goodsorder
#项目生成文件输出目录
#output_dir:  "/Users/chunxiaoli/IdeaProjects/"
output_dir:  "./"
type: "rpc"
#maven groupId
group_id: "com.chunxiao.mall"
#dubbo rpc owner
owner: chuxniao

#json_file controller cgi protocol file
cgi_json_file: "app.json"

#logback config template
log_config_file: "logback.xml"


#application.properties template
application_properties_template_path: "application.properties"

#mybatis config
mybatis:
  host: "127.0.0.1"
  port: "3307"
  username: root
  password: "4r3e2w1q"
  database: chunxiao_mall
  encoding: utf-8
  db_type:  "MySQL"
  tables:
          -   table_name: t_goods_order
              domain_name: GoodsOrder
