---
#项目名称
name: app
#项目生成文件输出目录
output_dir:  "./"
type: "web"
#maven groupId
group_id: "com.chunxiao.dev"
#dubbo rpc owner
owner: chuxniao

#json_file controller cgi protocol file
cgi_json_file: "app.json"

#logback config template
log_config_file: "logback.xml"

#rpc service pom template path
service_provider_pom_template: "pom.xml"

#application.properties template
application_properties_template_path: "application.properties"











